# config.yaml

# Configurazione MySQL
mysql:
  host: localhost
  database: venditori_db
  user: app_user
  password: Informatic1992.-

# Configurazione dell'Autenticazione
auth:
  credentials:
    usernames:
      paolo_patelli:
        email: paolo.patelli@salesflow.it  # ğŸ“§ Email dell'utente
        name: Paolo Patelli                  # ğŸ“ Nome completo dell'utente
        password: "$2b$12$MUQY2jX69VgqGE2lfmb7huJIhhI0hAV6Tk2nEW9Is0DQAGna9nzta"  # ğŸ” Password hashata

  cookie:
    expiry_days: 30                      # ğŸ“… Durata del cookie in giorni
    key: 192f6b314947a46e3845c8e9d4a08eec  # ğŸ”‘ Chiave segreta per il cookie (generata tramite script Python)
    name: venditori_app_cookie            # ğŸª Nome del cookie
